"""Create all EZRealtor tables

Revision ID: 2669b6114531
Revises: feb2223c65e9
Create Date: 2025-10-13 01:54:36.165189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2669b6114531'
down_revision = 'feb2223c65e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###