"""Add agent customization fields

Revision ID: cb8a7703cd53
Revises: 34b6b21580a3
Create Date: 2025-10-13 03:24:03.482495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8a7703cd53'
down_revision = '34b6b21580a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('agents', sa.Column('headshot_url', sa.String(length=500), nullable=True))
    op.add_column('agents', sa.Column('brand_primary_color', sa.String(length=7), nullable=True))
    op.add_column('agents', sa.Column('brand_secondary_color', sa.String(length=7), nullable=True))
    op.add_column('agents', sa.Column('brand_accent_color', sa.String(length=7), nullable=True))
    op.add_column('agents', sa.Column('buyer_page_headline', sa.String(length=200), nullable=True))
    op.add_column('agents', sa.Column('buyer_page_subtitle', sa.String(length=300), nullable=True))
    op.add_column('agents', sa.Column('valuation_page_headline', sa.String(length=200), nullable=True))
    op.add_column('agents', sa.Column('valuation_page_subtitle', sa.String(length=300), nullable=True))
    op.add_column('agents', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('agents', sa.Column('license_number', sa.String(length=50), nullable=True))
    op.add_column('agents', sa.Column('brokerage_name', sa.String(length=200), nullable=True))
    op.add_column('agents', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('agents', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    op.add_column('agents', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    op.add_column('agents', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('agents', sa.Column('submit_button_text', sa.String(length=100), nullable=True))
    op.add_column('agents', sa.Column('success_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'success_message')
    op.drop_column('agents', 'submit_button_text')
    op.drop_column('agents', 'linkedin_url')
    op.drop_column('agents', 'instagram_url')
    op.drop_column('agents', 'facebook_url')
    op.drop_column('agents', 'website_url')
    op.drop_column('agents', 'brokerage_name')
    op.drop_column('agents', 'license_number')
    op.drop_column('agents', 'title')
    op.drop_column('agents', 'valuation_page_subtitle')
    op.drop_column('agents', 'valuation_page_headline')
    op.drop_column('agents', 'buyer_page_subtitle')
    op.drop_column('agents', 'buyer_page_headline')
    op.drop_column('agents', 'brand_accent_color')
    op.drop_column('agents', 'brand_secondary_color')
    op.drop_column('agents', 'brand_primary_color')
    op.drop_column('agents', 'headshot_url')
    op.drop_column('agents', 'logo_url')
    # ### end Alembic commands ###